addons:
  ssh_known_hosts: 77.47.207.42

before_install:
- chmod 777 key.rsa.enc
- openssl aes-256-cbc -K $encrypted_a6b16146e8d4_key -iv $encrypted_a6b16146e8d4_iv -in key.rsa.enc -out ssh/key.rsa -d

after_success:
- chmod 777 ssh/key.rsa
- eval "$(ssh-agent -s)"
- ssh-add ssh/key.rsa
- pwd
